# Generated by Django 4.2.6 on 2023-11-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child_name",
                    models.CharField(max_length=100, verbose_name="Имя ребенка"),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "parent_name",
                    models.CharField(max_length=100, verbose_name="Имя родителя"),
                ),
            ],
            options={
                "verbose_name": "Ребенок",
                "verbose_name_plural": "Дети",
            },
        ),
        migrations.CreateModel(
            name="EducationalMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Учебный материал",
                "verbose_name_plural": "Учебные материалы",
            },
        ),
        migrations.CreateModel(
            name="ParentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_description",
                    models.TextField(verbose_name="Описание запроса"),
                ),
                (
                    "created_dt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beforeschool.child",
                        verbose_name="Идентификатор ребенка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос родителя",
                "verbose_name_plural": "Запросы родителей",
            },
        ),
        migrations.CreateModel(
            name="EducationalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(
                        max_length=100, verbose_name="Название активности"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата проведения")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beforeschool.child",
                        verbose_name="Идентификатор ребенка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательная активность",
                "verbose_name_plural": "Образовательные активности",
            },
        ),
    ]
